dev-status404/fundmate-be

package-lock.json, package.json
- 공통으로 사용할 라이브러리 설치
```
typeorm                              // ORM
dotenv                               // env
helmet                               // 보안 헤더 
cors                                 // CORS 미들웨어
express-validator                    // 입력 검증
pino                                 // 빠른 로거 라이브러리
http-status-codes                    // 상태코드
jsonwebtoken                         // JWT 처리
mysql2                               // DB
swagger-ui-express                   // API 문서
```
=> build: 공용 라이브러리 설치

.github/workflows/cd.yml
=> hotfix: cd 시행 시점 변경

apps/funding-service/src/controller/MainController.ts, apps/funding-service/src/controller/OptionController.ts, apps/funding-service/src/data-source.ts, apps/funding-service/src/routes/MainRouter.ts, shared/entities/src/funding-entities/OptionData.ts, shared/entities/src/funding-entities/Project.ts, shared/entities/src/index.ts, shared/entities/src/interaction-entities/Like.ts
- "찜한 프로젝트 조회"에 사용할 Like Entity를 추가했습니다
=> chore: Like Entity 추가

apps/api-gateway/src/controllers/api-controller.ts, apps/payment-service/src/routes/payment-route.ts, apps/payment-service/src/routes/reservation-route.ts
- auth문제로 header에 쿠키가 포함될 수 있도록하는 함수를 추가함
=> hotfix: gateway 라우터 수정

apps/funding-service/src/controller/FundingController.ts, apps/funding-service/src/controller/OptionController.ts, apps/funding-service/src/controller/ProfileController.ts
=> feat: 프로젝트 상세 조회 API 개발

apps/funding-service/src/controller/MainController.ts
=> fix: 최근 조회한 프로젝트가 없습니다 -> 빈 배열 리턴

apps/api-gateway/src/controllers/api-controller.ts, apps/auth-service/src/middleware/ensureAuthorization.ts, apps/funding-service/src/modules/ensureAuthorization.ts, apps/interaction-service/src/modules/ensureAuthorization.ts
- 어떤 작업을 했는지 간단히 설명해주세요.
- 관련된 이슈 번호: #123
작업 결과물이 있다면 첨부해주세요.
리뷰어가 알아야 할 사항이 있다면 적어주세요.
=> hotfix: 타입단언 수정

apps/funding-service/src/controller/OptionController.ts
- userId 검증을 통해 createOption 보안 문제 해결
=> hotfix: createOption 보안 문제 해결 (userId 검증)

apps/user-service/src/controller/FollowController.ts, apps/user-service/src/controller/MyPageController.ts, apps/user-service/src/controller/UserPageController.ts
- 외부 서버에서 받아온 데이터 배열 없이 단일 형태로 반환되도록 수정
- 결제 서버에서 받아오는 엔드포인트 수정
=> refactor: 외부 서버에서 받아온 데이터 배열 없이 단일 형태로 반환되도록 수정, 결제 서버에서 받아오는 엔드포인트 수정

apps/funding-service/src/controller/OptionController.ts, apps/funding-service/src/routes/OptionRouter.ts
=> feat: option 삭제 API 구현

apps/api-gateway/src/main.ts
=> feat: cors * 적용

apps/auth-service/src/controller/AuthController.ts, apps/auth-service/src/controller/OAuthController.ts
=> fix: accessToken maxAge 30분으로 수정

shared/entities/src/index.ts, shared/entities/src/payment-entities.ts, shared/logger/src/lib/logger.ts
=> fix: payments database -> dev

apps/funding-service/src/controller/FundingController.ts, apps/funding-service/src/controller/OptionController.ts, apps/funding-service/src/routes/FundingRouter.ts, apps/funding-service/src/routes/OptionRouter.ts
- 기존 옵션 생성 로직의 치명적인 설계 오류를 발견했습니다.
옵션 -> 프로젝트 순으로 데이터가 생성되는데, 프로젝트를 생성하지 않아도 옵션 값은 DB에 저장되어 있었습니다. 
(DB에 쓰레기값이 쌓임)
- 트렌젝션을 사용해 프로젝트 생성 -> 옵션 생성으로 로직을 변경하였습니다.
프로젝트 & 옵션 생성에 필요한 response는 공용 API 문서에 정리해 두었습니다.
response, request 값 확인 부탁드립니다!
[https://www.notion.so/API-request-response-231f93f59cb080da8c27e170afc3561b](url)
=> hotfix: 옵션 생성 설계 오류 수정

apps/user-service/src/controller/MyPageController.ts, apps/user-service/src/controller/UserPageController.ts
=> fix: 마이페이지 결제 서버 끌어오는 엔드포인트 수정

apps/funding-service/src/routes/FundingRouter.ts, apps/payment-service/src/routes/payment-route.ts, apps/payment-service/src/routes/reservation-route.ts, apps/payment-service/src/routes/statistics-route.ts, shared/config/src/lib/service-config.ts
- 통계페이지 결제 내역 페이지네이션 구현
- 결제정보 수정 수정
- 관련된 이슈 번호: #123
작업 결과물이 있다면 첨부해주세요.
리뷰어가 알아야 할 사항이 있다면 적어주세요.
=> Feat/payment -> dev

apps/user-service/src/controller/MyPageController.ts
- 마이 페이지 결제 관리 결제 서버 엔드 포인트 수정 및 req.query 추가
=> fix: 마이 페이지 결제 관리 결제 서버 엔드 포인트 수정 및 req.query 추가

apps/auth-service/src/controller/AuthController.ts
=> fix: 로그인 성공하면 닉네임 같이 띄워줌

.github/workflows/cd.yml
- cd에 .env 만들기 위해 추가함 s3설정에 필요한 것들을
=> feat: cd 수정

shared/logger/src/lib/logger.ts
- logger 정렬맞춤
- 관련된 이슈 번호: #123
작업 결과물이 있다면 첨부해주세요.
리뷰어가 알아야 할 사항이 있다면 적어주세요.
=> fix: logger 수정

apps/funding-service/src/controller/FundingController.ts
- funding detail - 집나간 user image_id 데려왔어요!
=> hotfix: 집나간 user_image_id 찾아오기

shared/config/src/lib/service-config.ts
=> fix: public-service 경로 수정

apps/api-gateway/src/main.ts
- 어떤 작업을 했는지 간단히 설명해주세요.
- 관련된 이슈 번호: #123
작업 결과물이 있다면 첨부해주세요.
리뷰어가 알아야 할 사항이 있다면 적어주세요.
=> fix: 안쓰는 request,response삭제

apps/funding-service/src/controller/FundingController.ts, apps/funding-service/src/modules/addLikedStatus.ts, apps/public-service/src/modules/GetAccessToken.ts, package-lock.json, package.json
=> feat: liked 좋아요 여부 조회 로직 추가

apps/auth-service/src/controller/OAuthController.ts
=> fix: 소셜 로그인 후 리다이렉트할 url 수정
